# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nell Waliczek
tagline: Principal Engineer, W3C Spec Editor, Maker
email: NellWaliczek@gmail.com
description:  Nell Waliczek is a Principal Engineer with AWS specializing in Virtual Reality and Augmented Reality with <a href="https://aws.amazon.com/sumerian/" target="_blank">Amazon Sumerian</a>.  She is the Spec Editor of the <a href="https://www.w3.org/TR/webxr/" target="_blank">W3C WebXR Device API</a> and Amazon's representative to the <a href="https://www.w3.org" target="_blank">W3C</a>.  Outside of work she likes building stuff with her kids using some of her favorite tools, the table saw and the serger.
url: "https://nell.dev"
baseurl: ""
twitter_username: NellWaliczek
github_username:  NellWaliczek

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
